### ISSUE TITLE
No option to add my own server ID, directed to this page.

### ISSUE THREAD

**Issue by Sehbaz** [navn-r/standup-bot#6]
![image](https://user-images.githubusercontent.com/7823496/160767871-77853421-28df-46ce-b3dd-919bbb22b91b.png)

**Comment by navn-r** [comment]
Hey @Sehbaz, thanks for raising the issue!

On the `README.md`...
>  You'll need to fill in `YOUR_CLIENT_ID` with your bots client id.

To create a Discord bot, follow the instructions [here](https://discord.com/developers/docs/intro), then simply update the url as need be. 

Thanks again.

**Comment by Sehbaz** [comment]
@navn-r 👍🏻
